server:
  port: 8888
  servlet:
    context-path: /pttapp

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://218.247.237.138:3306/wfchat?useUnicode=true&characterEncoding=utf8
    username: root
    password: speedata
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 90000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 1800000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

  #解决页面中文乱码
  http:
    encoding:
      force: true

  #页面拦截器
  mvc:
    static-path-pattern: /html/**

mybatis:
  mapper-locations: classpath:mappings/*.xml
  type-aliases-package: cn.wildfirechat.app.entity
  #支持驼峰式命名
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  config: classpath:log4j2.xml

#redis:
#  keyPrefix: jeeplatform     # Redis数据库索引（默认为0）
#  host: 172.17.133.168 # Redis服务器地址 （默认为127.0.0.1）
#  port: 6379      # Redis服务器连接端口 （默认为6379）
#  password: redis_liuchunhe    # Redis服务器连接密码（默认为空）


